### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by jgrenat** [eshvedai/react-starter-kit#1]
Hello,

Thanks for your starter pack, I'm starting to look at it.
The `npm install` is broken for now, there's a dependency missing: `babel-register`. Another problem: react-router@1.0.2 only wants history@1.13.x.

jgrenat

**Comment by eshvedai** [comment]
Hey,

@jgrenat, thanks for reviewing the repo, I've added babel-register as a dev dependency.
Unmet Peer Dependency warning is known issue, please review https://github.com/rackt/react-router/issues/2682
React-router team is going to fix that in next release.

**Comment by jgrenat** [comment]
Thanks! :)
